version: 2

project_name: kubera

before:
  hooks:
    - go mod tidy
    - go fmt ./...
    - go vet ./...

builds:
  - main: .
    binary: kubera
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.ShortCommit}} -X main.date={{.Date}}

archives:
  - formats:
      - tar.gz
    name_template: "kubera_{{.Version}}_{{.Os}}_{{.Arch}}"
    format_overrides:
      - goos: windows
        formats:
          - zip

checksum:
  name_template: "kubera_{{.Version}}_checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"

snapshot:
  version_template: "{{.Tag}}-dev"

release:
  github:
    owner: shishiro26
    name: Kubera
